# -*- coding: utf-8 -*-
"""Password_Strength_Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3dGN9WNP1HLht7ojJsmb6sxbGgZc-P5
"""

!pip install zxcvbn

import re
import math
from zxcvbn import zxcvbn

def calculate_entropy(password):
    charset = 0

    if re.search(r'[a-z]', password):
        charset += 26
    if re.search(r'[A-Z]', password):
        charset += 26
    if re.search(r'[0-9]', password):
        charset += 10
    if re.search(r'[^a-zA-Z0-9]', password):
        charset += 32

    if charset == 0:
        return 0

    entropy = len(password) * math.log2(charset)
    return round(entropy, 2)

def has_sequence(password):
    sequences = ["abcdefghijklmnopqrstuvwxyz", "0123456789"]

    for seq in sequences:
        for i in range(len(seq) - 2):
            if seq[i:i+3] in password.lower():
                return True
    return False

def advanced_password_strength(password):
    score = 0
    feedback = []

    # Length
    if len(password) >= 12:
        score += 25
    elif len(password) >= 8:
        score += 15
    else:
        feedback.append("Password is too short")

    # Upper & Lower
    if re.search(r'[A-Z]', password) and re.search(r'[a-z]', password):
        score += 15
    else:
        feedback.append("Use both uppercase and lowercase letters")

    # Numbers
    if re.search(r'[0-9]', password):
        score += 10
    else:
        feedback.append("Add numbers")

    # Special characters
    if re.search(r'[^a-zA-Z0-9]', password):
        score += 15
    else:
        feedback.append("Add special characters")

    # Repetition
    if len(set(password)) < len(password) * 0.7:
        feedback.append("Too many repeated characters")
    else:
        score += 10

    # Sequential check
    if has_sequence(password):
        feedback.append("Avoid sequential patterns like abc or 123")
    else:
        score += 10

    # Entropy
    entropy = calculate_entropy(password)
    if entropy > 60:
        score += 15
    else:
        feedback.append("Low entropy password")

    # Normalize score
    score = min(score, 100)

    # Strength label
    if score < 30:
        strength = "Very Weak"
    elif score < 50:
        strength = "Weak"
    elif score < 70:
        strength = "Medium"
    elif score < 85:
        strength = "Strong"
    else:
        strength = "Very Strong"

    return {
        "Score": score,
        "Strength": strength,
        "Entropy": entropy,
        "Feedback": feedback
    }

def crack_time_estimation(password):
    result = zxcvbn(password)
    return result['crack_times_display']['offline_slow_hashing_1e4_per_second']

password = input("Enter password to check: ")

result = advanced_password_strength(password)
crack_time = crack_time_estimation(password)

print("\n🔐 Password Strength Report")
print("-" * 30)
print("Strength      :", result["Strength"])
print("Score         :", result["Score"], "/ 100")
print("Entropy       :", result["Entropy"], "bits")
print("Crack Time    :", crack_time)

print("\n🛠 Suggestions:")
if result["Feedback"]:
    for tip in result["Feedback"]:
        print("-", tip)
else:
    print("Excellent password! No improvements needed.")